# Generated by Django 5.1.6 on 2025-03-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecciones', '0002_alter_producto_categoria_alter_producto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='colecciones.producto')),
            ],
            options={
                'verbose_name': 'Foto de producto',
                'verbose_name_plural': 'Fotos de productos',
                'ordering': ['orden'],
            },
        ),
    ]
